name: Android CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build_debug:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build debug APK
        run: ./gradlew :fm-dx-app:assembleDebug
      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: fm-dx-app-debug.zip
          path: android/fm-dx-app/build/outputs/apk/debug/fm-dx-app-debug.apk
          retention-days: 30

  build_release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build release APK
        run: ./gradlew :fm-dx-app:assembleRelease
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: fm-dx-app-release.zip
          path: android/fm-dx-app/build/outputs/apk/release/fm-dx-app-release.apk
          retention-days: 30
